### PR TITLE
Liquibase Updates 

### PR DESCRIPTION
**Pull request by r2liquibase**
Thanks for inviting me to join the db schema You Choose episode. I have updated some information about Liquibase.

### CODE REVIEW

**Comment by vfarcic** [comment]
It says that it is under "Non-CNCF Member Products/Projects" when applying filters under "Project" in the left-hand menu. Was it donated recently and was still not updated on the CNCF website?

**Comment by r2liquibase** [comment]
Thanks, @vfarcic . I should have removed that after emailing with @wiggitywhitney . She helped me understand what you and her were looking for.  Liquibase is not a CNCF Project, rather a member of the CNCF Landscape.

I updated the PR comment above. 

Please let me know what other information we can provide to help make a great stream/recording. Thanks!

**Comment by vfarcic** [comment]
No worries. CNCF landscape is confusing (at least to me).

Did you arrange with @wiggitywhitney to be a guest on the show?

**Comment by r2liquibase** [comment]
I believe we have arranged it for March 14th. 

How best to help you with the information for the show? Thanks!

**Comment by vfarcic** [comment]
There's not much else (apart from coming to the show). Typically, @wiggitywhitney or I add short descriptions to READMEs. If you want, you can add Liquibase or even a general description to https://github.com/vfarcic/cncf-demo/blob/main/manuscript/db-schema/README.md. If you take a look at those from the episodes we already did, you can get the feeling of the structure and the scope.

**Pull request closed without merging**
